### ISSUE TITLE
Kaiji malware

### ISSUE THREAD

**Issue by dkragen** [flathub/com.github.Murmele.Gittyup#33]
Clamav found Kaiji malware:

/var/lib/flatpak/app/com.github.Murmele.Gittyup/x86_64/stable/35e7e18ebf30ec9e05c50925eaecc1f2af2fe196754f72b105a340a4b5566f9d/files/bin/git-lfs: Unix.Malware.Kaiji-10003916-0 FOUND

**Comment by Murmele** [comment]
Thanks for reporting, is it the version 1.3.0?

**Comment by r-tae** [comment]
@Murmele @dkragen This was a false positive from ClamAV, you can see details here https://github.com/Cisco-Talos/clamav/issues/944

They removed `Unix.Malware.Kaiji-10003916-0` from their DB a few hours after this issue was created, so if I understand things correctly it'll stop reporting an issue by tomorrow.

**Comment by Murmele** [comment]
@r-tae thanks for the clarification
