### ISSUE TITLE
Why is org.freedesktop.Flatpak required?

### ISSUE THREAD

**Issue by bbhtt** [flathub/com.github.Murmele.Gittyup#38]
It was added in https://github.com/flathub/com.github.Murmele.Gittyup/commit/0440ebbfa011dd89c41096069234f070da978212 without any explanation.

Why is it required?

**Comment by Murmele** [comment]
Hmm I actually don't remember, I have to check the mergerequest in the Gittyup repository why it was added

**Comment by Murmele** [comment]
# Spawn commands outside of flatpak (https://unix.stackexchange.com/questions/412869/how-to-allow-gui-application-in-flatpak-to-run-cli-tool)

You may use [flatpak-spawn](http://docs.flatpak.org/en/latest/flatpak-command-reference.html) to run commands in a different environment.
However, usually you want to spwan the commands on the host system, thus breaking out of the sandbox. To do so, you obviously need to weaken the sandbox of the flatpak. Just add this permission:

flatpak override com.packagename.App `--talk-name=org.freedesktop.Flatpak`

Afterwards, you can run` flatpak-spawn --host` to run commands outside of the flatpak from the host.

---
This is required to be able to execute external commands like the difftool or the mergetool, otherwise it is not possible to use external diff/merge tools

**Comment by bbhtt** [comment]
> This is required to be able to execute external commands like the difftool or the mergetool, otherwise it is not possible to use external diff/merge tools

I'd suggest including one difftool (/bin/diff is already available in the runtime) and one mergetool in the sandbox and removing that. 

Mergetool is complicated because most of them are GUI, but I wonder if you can include something like `vimdiff`.

This is a very broad access that gives the application ability to execute any commands on host bypassing the sandbox.

Those who need special access can do so using Flatseal or flatpak override, the default offered should be secure.

**Comment by Murmele** [comment]
Yes mergetool is a big thing, but I think a lot people have different taste which one they prefer. I prefer most kdiff3, but some prefer meld and so on. Not keeping this generic would make it quite problematic and less userfriendly
